config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'welcome#index'
  get '/auth/google_oauth2', as: 'google_login'
  get '/auth/google_oauth2/callback', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  namespace :user do
    get '/dashboard', to: 'dashboard#show'
    get '/compare', to: 'compare#show'
    get '/search', to: 'search#show'
    get '/register_state/:id/edit', to: 'register#edit'
    patch '/register_state/:id', to: 'register#update'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :uid, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  def has_state?
    state.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user,
                :compare_path?,
                :search_path?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def compare_path?
    request.path == "/user/compare"
  end

  def search_path?
    request.path == "/user/search"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    does_user_exist ? login_registered_user : create_and_login_new_user
  end

  def destroy
    logout_and_flash
  end

  private

  def user_params
    {
      uid: gather_uid,
      first_name: gather_first_name,
      last_name: gather_last_name,
      email: gather_email
    }
  end

  def gather_uid
    request.env["omniauth.auth"]["uid"]
  end

  def gather_first_name
    request.env["omniauth.auth"]["info"]["first_name"]
  end

  def gather_last_name
    request.env["omniauth.auth"]["info"]["last_name"]
  end

  def gather_email
    request.env["omniauth.auth"]["info"]["email"]
  end

  def create_and_login_new_user
    user = User.create(user_params)
    login_and_redirect(user)
  end

  def login_registered_user
    user = User.find_by(uid: gather_uid)
    login_and_redirect(user)
  end

  def does_user_exist
    User.exists?(uid: gather_uid)
  end

  def login(user)
    session[:user_id] = user.id
  end

  def redirect(user = nil)
    redirect_to "/user/register_state/#{user.id}/edit" unless user.has_state?
    redirect_to '/user/dashboard' if user.has_state?
  end

  def login_and_redirect(user)
    login(user)
    redirect(user)
  end

  def logout_and_flash
    session[:user_id] = nil
    flash[:success] = "You have left. Goodbye!"
    redirect_to '/'
  end
end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
  before_action :require_login

  def require_login
    render file: "/public/404" unless current_user
  end
end

app/controllers/user/compare_controller.rb
class User::CompareController < User::BaseController
  def show; end
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < User::BaseController
  def show; end
end

app/controllers/user/register_controller.rb
class User::RegisterController < User::BaseController
  def edit; end

  def update
    current_user.update(state: params[:state])
    redirect_to "/user/dashboard"
  end
end

app/controllers/user/search_controller.rb
class User::SearchController < User::BaseController
  def show; end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrimeTime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_user %>
      <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="/">Hi <%= current_user.first_name %></a>
        <form class="form-inline">
          <%= link_to "Search", "/user/search", role: "button", class: "btn btn-outline-success" unless search_path? %>
          <div style="padding-left: 10px;">
            <%= link_to "Compare", "/user/compare", role: "button", class: "btn btn-outline-primary" unless compare_path? %>
          </div>
          <div style="padding-left: 10px;">
            <%= link_to "Leave", "/logout", method: :delete, role: "button", class: "btn btn-outline-danger" %>
          </div>
        </form>
      </nav>
    <% end %>

    <% flash.each do |name, msg| %>
      <div class= "<%=name%>-flash">
        <p><%= msg %></p>
      </div>
    <% end %>
    <p id="js-flash"></p>

    <%= yield %>
  </body>
</html>

app/views/user/compare/show.html.erb
<section class='state-1'>
  <%= select_tag :state, options_for_select(us_states), class: 'state', id: 'state1' %>
</section>
<section class='state-2'>
  <%= select_tag :state, options_for_select(us_states), class: 'state', id: 'state2' %>
</section>
<!-- Compare button will need a listener to display both stat windows for each state -->
<section>
  <button type="button" class="btn btn-outline-primary" id="compare-button">Compare</button>
</section>
<!-- Tables should be empty until we click compare to display them, need to learned AJAX -->

<table class='table table-striped table-dark state-1-table'>
<h2 class="text-center p-2"><strong>Stats</strong></h2>
  <thead>
    <tr class='state-headers'>
      <th scope="col-3">Crime</th>
      <th scope="col-3">Total Occurrence</th>
      <th scope="col-3">Percent Against State's Total Crimes</th>
      <th scope="col-3">Percent Against National Occurrence</th>
    </tr>
  </thead>

  <tbody>
    <tr class="aggravated-assault">
      <th scope="row">Aggravated Assault</th>
    </tr>
    <tr class="homicide">
      <th scope="row">Homicide</th>
    </tr>
    <tr class="rape">
      <th scope="row">Rape</th>
    </tr>
    <tr class="property-crime">
      <th scope="row">Property Crime</th>
    </tr>
    <tr class="arson">
      <th scope="row">Arson</th>
    </tr>
  </tbody>
</table>

<table class='table table-striped table-dark state-2-table'>
<h2 class="text-center p-2"><strong>Stats</strong></h2>
  <thead>
    <tr class='state-headers'>
      <th scope="col-3">Crime</th>
      <th scope="col-3">Total Occurrence</th>
      <th scope="col-3">Percent Against State's Total Crimes</th>
      <th scope="col-3">Percent Against National Occurrence</th>
    </tr>
  </thead>

  <tbody>
    <tr class="aggravated-assault">
      <th scope="row">Aggravated Assault</th>
    </tr>
    <tr class="homicide">
      <th scope="row">Homicide</th>
    </tr>
    <tr class="rape">
      <th scope="row">Rape</th>
    </tr>
    <tr class="property-crime">
      <th scope="row">Property Crime</th>
    </tr>
    <tr class="arson">
      <th scope="row">Arson</th>
    </tr>
  </tbody>
</table>

app/views/user/dashboard/show.html.erb
<p>Registered email: <%= current_user.email %></p>
<p>State of Residence: <span id='user-state'><%= current_user.state %></span></p>

<table class="table table-striped table-dark state-stats">
<h2 class="text-center p-2"><strong>Your State's Stats</strong></h2>
  <thead>
    <tr class='state-headers'>
      <th scope="col-3">Crime</th>
      <th scope="col-3">Total Occurrence</th>
      <th scope="col-3">Percent Against State's Total Crimes</th>
      <th scope="col-3">Percent Against National Occurrence</th>
    </tr>
  </thead>

  <tbody>
    <tr class="aggravated-assault">
      <th scope="row">Aggravated Assault</th>
    </tr>
    <tr class="homicide">
      <th scope="row">Homicide</th>
    </tr>
    <tr class="rape">
      <th scope="row">Rape</th>
    </tr>
    <tr class="property-crime">
      <th scope="row">Property Crime</th>
    </tr>
    <tr class="arson">
      <th scope="row">Arson</th>
    </tr>
  </tbody>
</table>

app/views/user/register/edit.html.erb
<h2>Please select your current state of residence from the dropdown below</h2>

<%= form_tag "/user/register_state/#{current_user.id}", method: :patch do %>
  <%= select_tag :state, options_for_select(us_states) %>
  <%= submit_tag "Submit" %>
<% end %>

app/views/user/search/show.html.erb
<section class='state-selector'>
  <%= select_tag :state, options_for_select(us_states), class: 'state' %>
</section>

<table class="table table-striped table-dark state-table">
<h2 class="text-center p-2"><strong>Stats</strong></h2>
  <thead>
    <tr class='state-headers'>
      <th scope="col-3">Crime</th>
      <th scope="col-3">Total Occurrence</th>
      <th scope="col-3">Percent Against State's Total Crimes</th>
      <th scope="col-3">Percent Against National Occurrence</th>
    </tr>
  </thead>

  <tbody>
    <tr class="aggravated-assault">
      <th scope="row">Aggravated Assault</th>
    </tr>
    <tr class="homicide">
      <th scope="row">Homicide</th>
    </tr>
    <tr class="rape">
      <th scope="row">Rape</th>
    </tr>
    <tr class="property-crime">
      <th scope="row">Property Crime</th>
    </tr>
    <tr class="arson">
      <th scope="row">Arson</th>
    </tr>
  </tbody>
</table>

app/views/welcome/index.html.erb
<h1 class="text-center p-4"><strong>Welcome To Crime Time!</strong></h1>
<section class="text-center">
  <%= link_to "Login with Google", google_login_path, class: "btn btn-lg btn-outline-success" %>
</section></br>

<table class="table table-striped table-dark national-stats">
<h2 class="text-center p-2"><strong>National Stats</strong></h2>
<thead>
  <tr>
    <th scope="col-4">Crime</th>
    <th scope="col-4">Total Occurrence</th>
    <th scope="col-4">Percentage of Total Crimes</th>
  </tr>
</thead>

<tbody>
  <tr class="aggravated-assault">
    <th scope="row">Aggravated Assault</th>
  </tr>
  <tr class="homicide">
    <th scope="row">Homicide</th>
  </tr>
  <tr class="rape">
    <th scope="row">Rape</th>
  </tr>
  <tr class="property-crime">
    <th scope="row">Property Crime</th>
  </tr>
  <tr class="arson">
    <th scope="row">Arson</th>
  </tr>
</table>
</tbody>

<table class="table table-striped table-dark top-ten">
<h2 class="text-center p-2"><strong>Top Ten Most Wanted</strong></h2>
  <thead>
    <tr>
      <th scope="col-6">Fugitive</th>
      <th scope="col-6">Last Known Location</th>
    </tr>
  </thead>

  <tbody>
    <tr class='fugitive-one'>
      <th scope="row">Eugene Palmer</th>
      <td>Unknown</td>
    </tr>
    <tr class='fugitive-two'>
      <th scope="row">Santiago Villalba Mederos</th>
      <td>Unknown</td>
    </tr>
    <tr class='fugitive-three'>
      <th scope="row">Rafael Caro-Quintero</th>
      <td>Unknown</td>
    </tr>
    <tr class='fugitive-four'>
      <th scope="row">Robert William Fisher</th>
      <td>Unknown</td>
    </tr>
    <tr class='fugitive-five'>
      <th scope="row">Bhadreshkumar Chetanbhai Patel</th>
      <td>Unknown</td>
    </tr>
    <tr class='fugitive-six'>
      <th scope="row">Alejandro Rosales Castillo</th>
      <td>Unknown</td>
    </tr>
    <tr class='fugitive-seven'>
      <th scope="row">Arnoldo Jimenez</th>
      <td>Unknown</td>
    </tr>
    <tr class='fugitive-eight'>
      <th scope="row">Jason Derek Brown</th>
      <td>Unknown</td>
    </tr>
    <tr class='fugitive-nine'>
      <th scope="row">Yaser Abdel Said</th>
      <td>Unknown</td>
    </tr>
    <tr class='fugitive-ten'>
      <th scope="row">Alexis Flores</th>
      <td>Unknown</td>
    </tr>
  </tbody>
</table></br>